name: "floor"

createVisualShape:
  shapeType: "GEOM_PLANE"
  planeNormal: [0, 0, 1]

createCollisionShape:
  shapeType: "GEOM_PLANE"
  planeNormal: [0, 0, 1]

changeDynamics:
  lateralFriction: 0.7
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.5

object_tf:
  tf_id: "floor_base"