name: "pushing_box"

broadcast_hz: 60

createVisualShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.05, 0.06, 0.035]
  rgbaColor: [1, 1, 0, 1]

createCollisionShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.05, 0.06, 0.035]
  
baseMass: 0.5
basePosition: [0.5, 0, 0.77015]  # z = 0.077015 = 0.01515+0.72+0.035 table half height + table center height + box height
baseOrientation: [0, 0, 0, 1]

changeDynamics:
  lateralFriction: 0.7
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.5