name: "table"

createVisualShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.3, 0.5, 0.01515]
  rgbaColor: [0.8, 0.7, 0.5, 1.0]
  visualFramePosition: [0.5, 0.0, 0.72]

createCollisionShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.3, 0.5, 0.01515]
  collisionFramePosition: [0.5, 0.0, 0.72]


changeDynamics:
  lateralFriction: 1.0
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.0
  linearDamping: 0.04
  angularDamping: 0.04
  contactStiffness: 2000.0
  contactDamping: 0.7

object_tf:
  tf_id: "table_base"