controller_list:
  - name: fake_torso_controller
    joints:
      - CHEST_JOINT0
  - name: fake_larm_controller
    joints:
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
  - name: fake_rarm_controller
    joints:
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
  - name: fake_head_controller
    joints:
      - HEAD_JOINT0
      - HEAD_JOINT1
  - name: fake_body_controller
    joints:
      - CHEST_JOINT0
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
  - name: fake_whole_body_controller
    joints:
      - CHEST_JOINT0
      - HEAD_JOINT0
      - HEAD_JOINT1
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
initial:  # Define initial robot poses.
#  - group: torso
#    pose: home
