#
# Pybullet instance
#
connect:
  connection_mode: 'GUI'

setGravity:
  gravX: 0.0
  gravY: 0.0
  gravZ: -9.81
timeStep: 0.00416666666
start_pybullet_after_initialization: true
status_hz: 60

#
# Pybullet visualizer
#
configureDebugVisualizer:
  enable: 0
  flag: 'COV_ENABLE_GUI'

resetDebugVisualizerCamera:
  cameraDistance: 2.0
  cameraYaw: 0.0
  cameraPitch: -45.0
  cameraTargetPosition: [0.0, 0.0, 0.0]

#
# Pybullet objects
#
collision_objects:
  - "{nextage_picking}/config/rpbi/floor.yaml"
  - "{nextage_picking}/config/rpbi/table.yaml"
robots:
  - "{nextage_picking}/config/rpbi/nextage.yaml"
