/:
 robot_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 20
 four_wheel_controller:
  type: "four_wheel_steering_controller/FourWheelSteeringController"
  front_wheel: ['front_left_drive_wheel_joint', 'front_right_drive_wheel_joint']
  rear_wheel: ['rear_left_drive_wheel_joint', 'rear_right_drive_wheel_joint']
  front_steering: ['front_left_steering_joint', 'front_right_steering_joint']
  rear_steering: ['rear_left_steering_joint', 'rear_right_steering_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 25.0 # not tested here

  # Base frame_id
  base_frame_id: omni_4sw_body_link

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true
