gazebo_ros_control/pid_gains:
  front_left_steering_joint: {p: 25.0, i: 0.1, d: 0.5, antiwindup: true}
  front_right_steering_joint: {p: 25.0, i: 0.1, d: 0.5, antiwindup: true}
  rear_left_steering_joint: {p: 25.0, i: 0.1, d: 0.5, antiwindup: true}
  rear_right_steering_joint: {p: 25.0, i: 0.1, d: 0.5, antiwindup: true}
  #front_left_steering_joint: {p: 20.0, i: 3.0, d: 0.0, antiwindup: true}
  #front_right_steering_joint: {p: 20.0, i: 3.0, d: 0.0, antiwindup: true}
  #rear_left_steering_joint: {p: 20.0, i: 3.0, d: 0.0, antiwindup: true}
  #rear_right_steering_joint: {p: 20.0, i: 3.0, d: 0.0, antiwindup: true}
  front_left_drive_wheel_joint: {p: 3.0, i: 0.0, d: 0.0}
  front_right_drive_wheel_joint: {p: 3.0, i: 0.0, d: 0.0}
  rear_left_drive_wheel_joint: {p: 3.0, i: 0.0, d: 0.0}
  rear_right_drive_wheel_joint: {p: 3.0, i: 0.0, d: 0.0}
