/:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  

  # Position Controllers ---------------------------------------
  pillar_position_controller:
    type: effort_controllers/JointPositionController
    joint: pillar_body_joint
    pid: {p: 12500.0, i: 0.1, d: 50.0}
  



