gazebo_ros_control:
  pid_gains:
    fl_wheel_joint: {p: 1500,  d: 0, i: 0, i_clamp: 1}
    fr_wheel_joint: {p: 1500,  d: 0, i: 0, i_clamp: 1}
    rl_wheel_joint: {p: 1500,  d: 0, i: 0, i_clamp: 1}
    rr_wheel_joint: {p: 1500,  d: 0, i: 0, i_clamp: 1}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

donkey_velocity_controller:
  type: "mecanum_drive_controller/MecanumDriveController"
  front_left_wheel_joint: "fl_wheel_joint"
  back_left_wheel_joint: "rl_wheel_joint"
  front_right_wheel_joint: "fr_wheel_joint"
  back_right_wheel_joint: "rr_wheel_joint"
  publish_rate: 100
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.1
  joints:
    - fl_wheel_joint
    - fr_wheel_joint
    - rl_wheel_joint
    - rr_wheel_joint

  # Override URDF look-up for wheel separation since the parent link is not the base_link.
  wheel_separation_x: 0.5
  wheel_separation_y: 0.44
  wheel_radius: 0.1

  enable_odom_tf: true

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.5   # m/s^2
    y:
      has_velocity_limits    : true
      max_velocity           : 1.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.5   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.5
