odom_frame: odom
base_link_frame: base_link
world_frame: world
map_frame: world
sensor_timeout: 0.001

two_d_mode: true

frequency: 100

odom0: state_estimation/odometry
odom0_config: [true, true, false,
              false, false, true,
              false, false, false,
              false, false, false,
              false, false, false]
odom0_differential: true
odom0_queue_size: 200

imu0: state_estimation/imu
imu0_config: [false, false, false,
             false, false, false,
             false, false, false,
             true, true, true,
             false, false, false]
imu0_differential: true
imu0_queue_size: 200
imu0_remove_gravitational_acceleration: true

odom1: state_estimation/localization
odom1_config: [true, true, true,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]
odom1_differential: false
odom1_relative: false
odom1_queue_size: 200
