link_ee_right: "RARM_END_EFFECTOR_finger"
link_ee_left: "LARM_END_EFFECTOR_finger"
link_head: "CAMERA_HEAD_HEADING_Link"
link_ref: "teleop_ref"
link_gaze: "gaze_ref"
x_min: 0.2
x_max: 0.8
y_min: -0.5
y_max: 0.5
z_min: 0.73
z_max: 0.8
roll_min: 0
roll_max: 0
pitch_min: 0
pitch_max: 0
yaw_min: 0
yaw_max: 0
W_x: 10
W_y: 10
W_z: 20
W_roll: 0
W_pitch: 0
W_yaw: 0