/chonk/gazebo_ros_control:
  pid_gains:
    CHEST_JOINT0: {p: 1500, i: 0, d: 5}
    HEAD_JOINT0: {p: 1500, i: 0, d: 1}
    HEAD_JOINT1: {p: 1500, i: 0, d: 1}
    LARM_JOINT0: {p: 20000, i: 0.0, d: 10.0}
    LARM_JOINT1: {p: 40000, i: 0.0, d: 10.0}
    LARM_JOINT2: {p: 50000, i: 0.0, d: 10.0}
    LARM_JOINT3: {p: 5000, i: 0.0, d: 8.0}
    LARM_JOINT4: {p: 2000, i: 0.0, d: 15.0}
    LARM_JOINT5: {p: 600, i: 0.0, d: 1}
    RARM_JOINT0: {p: 20000, i: 0.0, d: 10.0}
    RARM_JOINT1: {p: 40000, i: 0.0, d: 10.0}
    RARM_JOINT2: {p: 50000, i: 0.0, d: 10.0}
    RARM_JOINT3: {p: 5000, i: 0.0, d: 8.0}
    RARM_JOINT4: {p: 2000, i: 0.0, d: 15.0}
    RARM_JOINT5: {p: 600, i: 0.0, d: 1}
    # RARM_left_inner_knuckle_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # RARM_left_inner_finger_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # RARM_right_outer_knuckle_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # RARM_finger_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # RARM_right_inner_knuckle_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # RARM_right_inner_finger_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # RARM_gripper_open_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # LARM_left_inner_knuckle_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # LARM_left_inner_finger_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # LARM_right_outer_knuckle_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # LARM_finger_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # LARM_right_inner_knuckle_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # LARM_right_inner_finger_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    # LARM_gripper_open_joint: {p: 20,  d: 0.01, i: 0.01, i_clamp: 1}
    fl_wheel_joint: {p: 5000,  d: 0.5, i: 0.01, i_clamp: 1}
    # fl_wheel_link_passive_joint: {p: 1500,  d: 0.5, i: 0.01, i_clamp: 1}
    fr_wheel_joint: {p: 5000,  d: 0.5, i: 0.01, i_clamp: 1}
    # fr_wheel_link_passive_joint: {p: 1500,  d: 0.5, i: 0.01, i_clamp: 1}
    rl_wheel_joint: {p: 5000,  d: 0.5, i: 0.01, i_clamp: 1}
    # rl_wheel_link_passive_joint: {p: 1500,  d: 0.5, i: 0.01, i_clamp: 1}
    rr_wheel_joint: {p: 5000,  d: 0.5, i: 0.01, i_clamp: 1}
    # rr_wheel_link_passive_joint: {p: 1500,  d: 0.5, i: 0.01, i_clamp: 1}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

donkey_velocity_controller:
  type: "mecanum_drive_controller/MecanumDriveController"
  front_left_wheel_joint: "fl_wheel_joint"
  back_left_wheel_joint: "rl_wheel_joint"
  front_right_wheel_joint: "fr_wheel_joint"
  back_right_wheel_joint: "rr_wheel_joint"
  publish_rate: 100
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  # pose_covariance_diagonal: [0., 0., 0., 0., 0., 0.]
  # twist_covariance_diagonal: [0., 0., 0., 0., 0., 0.]
  cmd_vel_timeout: 0.1
  joints:
    - fl_wheel_joint
    - fr_wheel_joint
    - rl_wheel_joint
    - rr_wheel_joint

  # Override URDF look-up for wheel separation since the parent link is not the base_link.
  # wheel_separation_x: 0.5
  # wheel_separation_y: 0.44
  # wheel_radius: 0.1
  wheel_separation_x: 0.72
  wheel_separation_y: 0.5
  wheel_radius: 0.095

  enable_odom_tf: true

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.5   # m/s^2
    y:
      has_velocity_limits    : true
      max_velocity           : 1.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.5   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.5

# Robot config
streaming_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - CHEST_JOINT0
    - HEAD_JOINT0
    - HEAD_JOINT1
    - LARM_JOINT0
    - LARM_JOINT1
    - LARM_JOINT2
    - LARM_JOINT3
    - LARM_JOINT4
    - LARM_JOINT5
    - RARM_JOINT0
    - RARM_JOINT1
    - RARM_JOINT2
    - RARM_JOINT3
    - RARM_JOINT4
    - RARM_JOINT5
    # - fl_wheel_joint
    # - fl_wheel_link_passive_joint
    # - fr_wheel_joint
    # - fr_wheel_link_passive_joint
    # - rl_wheel_joint
    # - rl_wheel_link_passive_joint
    # - fl_wheel_joint
    # - rr_wheel_link_passive_joint
  RobotDescriptionParameter: /robot_description
  PositionSafetyFactor: 0.95
  VelocitySafetyFactor: 0.3
  AccelerationSafetyFactor: 0.002
  Kp: 200.0
  Kd: 100.0
  ExoticaValidityChecker:
    config: "{chonk_bringup}/config/chonk_collision.xml"


trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - CHEST_JOINT0
    - HEAD_JOINT0
    - HEAD_JOINT1
    - LARM_JOINT0
    - LARM_JOINT1
    - LARM_JOINT2
    - LARM_JOINT3
    - LARM_JOINT4
    - LARM_JOINT5
    - RARM_JOINT0
    - RARM_JOINT1
    - RARM_JOINT2
    - RARM_JOINT3
    - RARM_JOINT4
    - RARM_JOINT5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10

larm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - LARM_JOINT0
    - LARM_JOINT1
    - LARM_JOINT2
    - LARM_JOINT3
    - LARM_JOINT4
    - LARM_JOINT5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10

rarm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - RARM_JOINT0
    - RARM_JOINT1
    - RARM_JOINT2
    - RARM_JOINT3
    - RARM_JOINT4
    - RARM_JOINT5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10

botharms_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - LARM_JOINT0
    - LARM_JOINT1
    - LARM_JOINT2
    - LARM_JOINT3
    - LARM_JOINT4
    - LARM_JOINT5
    - RARM_JOINT0
    - RARM_JOINT1
    - RARM_JOINT2
    - RARM_JOINT3
    - RARM_JOINT4
    - RARM_JOINT5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10

head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - HEAD_JOINT0
    - HEAD_JOINT1
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10

torso_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - CHEST_JOINT0
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  100
  action_monitor_rate: 10
