link_ee_right: "RARM_changer_link"
link_ee_left: "LARM_changer_link"
link_head: "CAMERA_HEAD_HEADING_Link"
link_ref: "teleop_ref"
link_gaze: "gaze_ref"
x_min: 0.25
x_max: 0.55
y_min: -0.4
y_max: 0.1
z_min: 0.79
z_max: 1.00
roll_min: 0
roll_max: 0
pitch_min: 0
pitch_max: 0
yaw_min: -170.0
yaw_max: 170.0
W_x: 10
W_y: 10
W_z: 20
W_roll: 0
W_pitch: 0
W_yaw: 2.0